name: Java Tests

on:
  pull_request:
    branches:
      - 'next'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java Temurin 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        run: mvn clean install

      - name: Run tests
        run: mvn test